name: TestWorkflow
on:
  workflow_dispatch:
  repository_dispatch:
    types: [testworkflow]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - run: 
        git clone https://github.com/JensEhrhardt-eOPUS/Mittagsbot.git
        cd Mittagsbot
        ls
